#!/bin/sh

set -ev

SERVER_JAR="$SERVER_ROOT/$SERVER_ARTIFACT"

exec su socrata -c "exec /usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -XX:MaxMetaspaceSize=${MAX_META_SIZE} \
    -XX:CompressedClassSpaceSize=${COMPRESSED_CLASS_SIZE} \
    -Djava.net.preferIPv4Stack=true \
    -jar $SERVER_JAR"
