apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: image-resize-service
  description: |
    Resizes and crops images. This service only exists to make it harder to do a
    DOS attack against core-server with giant image requests.
  links:
    - title: Ops Doc
      url: "https://socrata.atlassian.net/wiki/spaces/ONCALL/pages/2158592212/OpsDoc+-+Image+Resize+Service"
  annotations:
    github.com/project-slug: socrata-platform/image-resize-service
    backstage.io/techdocs-ref: dir:.
    infrastructure: apps-marathon
spec:
  type: service
  owner: auth-and-discovery
  lifecycle: production
